### ISSUE TITLE
Updater uses bleeding edge anyways

### ISSUE THREAD

**Issue by Atmatm6** [BananaBerryInc/spit-fire-updater#1]
Since the updater just clones the original repository, people end up getting the most recent commit of [spit-fire](https://github.com/BananaBerryInc/spit-fire), defeating the purpose of the updater.

**Comment by johnnyw3** [comment]
Hmm, I really don't know what to say here. **Cloning the repo was kind of the point in the first place**, saving time by not having to go click "clone", extract the files, save the level, and finally continue, but I could defiantly work on this in the future. 

**Thanks for the suggestion!**

**Comment by johnnyw3** [comment]
I also want to mention this : **A lot of the people playing the game aren't git/github experts**, which is why it made it the way I did. The user would then go to github.com to get the update, and as well, would have to extract the files (they come in a zip), and place them into a new/existing folder, not to mention the other issues with this method.

In the future, I will work to improve this, but just a explanation for now. ;)
